/*
 * This file is generated by jOOQ.
 */
package generated_sources;


import generated_sources.tables.Mahasiswa;
import generated_sources.tables.records.MahasiswaRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MahasiswaRecord> MAHASISWA_PKEY = Internal.createUniqueKey(Mahasiswa.MAHASISWA, DSL.name("mahasiswa_pkey"), new TableField[] { Mahasiswa.MAHASISWA.ID }, true);
}
