/*
 * This file is generated by jOOQ.
 */
package generated_sources;


import generated_sources.tables.Mahasiswa;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.mahasiswa</code>.
     */
    public static final Mahasiswa MAHASISWA = Mahasiswa.MAHASISWA;
}
