/*
 * This file is generated by jOOQ.
 */
package generated_sources.tables;


import generated_sources.Keys;
import generated_sources.Public;
import generated_sources.tables.records.MahasiswaRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mahasiswa extends TableImpl<MahasiswaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mahasiswa</code>
     */
    public static final Mahasiswa MAHASISWA = new Mahasiswa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MahasiswaRecord> getRecordType() {
        return MahasiswaRecord.class;
    }

    /**
     * The column <code>public.mahasiswa.id</code>.
     */
    public final TableField<MahasiswaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mahasiswa.nama</code>.
     */
    public final TableField<MahasiswaRecord, String> NAMA = createField(DSL.name("nama"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mahasiswa.umur</code>.
     */
    public final TableField<MahasiswaRecord, Integer> UMUR = createField(DSL.name("umur"), SQLDataType.INTEGER, this, "");

    private Mahasiswa(Name alias, Table<MahasiswaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mahasiswa(Name alias, Table<MahasiswaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mahasiswa</code> table reference
     */
    public Mahasiswa(String alias) {
        this(DSL.name(alias), MAHASISWA);
    }

    /**
     * Create an aliased <code>public.mahasiswa</code> table reference
     */
    public Mahasiswa(Name alias) {
        this(alias, MAHASISWA);
    }

    /**
     * Create a <code>public.mahasiswa</code> table reference
     */
    public Mahasiswa() {
        this(DSL.name("mahasiswa"), null);
    }

    public <O extends Record> Mahasiswa(Table<O> child, ForeignKey<O, MahasiswaRecord> key) {
        super(child, key, MAHASISWA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MahasiswaRecord, Integer> getIdentity() {
        return (Identity<MahasiswaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MahasiswaRecord> getPrimaryKey() {
        return Keys.MAHASISWA_PKEY;
    }

    @Override
    public Mahasiswa as(String alias) {
        return new Mahasiswa(DSL.name(alias), this);
    }

    @Override
    public Mahasiswa as(Name alias) {
        return new Mahasiswa(alias, this);
    }

    @Override
    public Mahasiswa as(Table<?> alias) {
        return new Mahasiswa(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mahasiswa rename(String name) {
        return new Mahasiswa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mahasiswa rename(Name name) {
        return new Mahasiswa(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mahasiswa rename(Table<?> name) {
        return new Mahasiswa(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
